Harfler = "ACTCTTCTGGTCCCCACAGACTCAGAGAGAACCCACCATGGTGCTGTCTCCTGCCGACAAGACCAACGTCAAGGCCGCCTGGGGTAAGGTCGGCGCGCACGCTGGCGAGTATGGTGCGGAGGCCCTGGAGAGGATGTTCCTGTCCTTCCCCACCACCAAGACCTACTTCCCGCACTTCGACCTGAGCCACGGCTCTGCCCAGGTTAAGGGCCACGGCAAGAAGGTGGCCGACGCGCTGACCAACGCCGTGGCGCACGTGGACGACATGCCCAACGCGCTGTCCGCCCTGAGCGACCTGCACGCGCACAAGCTTCGGGTGGACCCGGTCAACTTCAAGCTCCTAAGCCACTGCCTGCTGGTGACCCTGGCCGCCCACCTCCCCGCCGAGTTCACCCCTGCGGTGCACGCCTCCCTGGACAAGTTCCTGGCTTCTGTGAGCACCGTGCTGACCTCCAAATACCGTTAAGCTGGAGCCTCGGTGGCCATGCTT"
sayaçA=0
sayaçG=0
sayaçT=0
sayaçC=0
for i in Harfler:
    if i=="A":
        sayaçA=sayaçA+1
    if i=="G":
        intG=intG+1
    if i=="T":
        intT=intT+1
    if i=="C":
        intC=intC+1
print("A sayısı="+str(sayaçA)+" adet","|","G sayısı="+str(sayaçG)+" adet","|","T sayısı="+str(sayaçT)+" adet","|","C sayısı="+str(sayaçC)+" adet")            