from itertools import *


def sayi_bilgisi(a):
    print({girdi: a.count(girdi) for girdi in a})

def other_sayi_bilgisi(b):
    sonuc = {"A":0,
    "C":0,
    "T":0,
    "G":0 }

    for i in b:
        if i == "A":
            sonuc["A"] = b.count(i)
        if i == "G":
            sonuc["G"] = b.count(i)
        if i == "C":
            sonuc["C"] = b.count(i)
        if i == "T":
            sonuc["T"] = b.count(i)

    print(sonuc)


other_sayi_bilgisi("ACGATGCTACGTACATCGTC")


sayi_bilgisi("ACTCTTCTGGTCCCCACAGACTCAGAGAGAACCCACCATGGTGCTGTCTCCTGCCGACAAGACCAACGTCAAGGCCGCCTGGGGTAAGGTCGGCGCGCACGCTGGCGAGTATGGTGCGGAGGCCCTGGAGAGGATGTTCCTGTCCTTCCCCACCACCAAGACCTACTTCCCGCACTTCGACCTGAGCCACGGCTCTGCCCAGGTTAAGGGCCACGGCAAGAAGGTGGCCGACGCGCTGACCAACGCCGTGGCGCACGTGGACGACATGCCCAACGCGCTGTCCGCCCTGAGCGACCTGCACGCGCACAAGCTTCGGGTGGACCCGGTCAACTTCAAGCTCCTAAGCCACTGCCTGCTGGTGACCCTGGCCGCCCACCTCCCCGCCGAGTTCACCCCTGCGGTGCACGCCTCCCTGGACAAGTTCCTGGCTTCTGTGAGCACCGTGCTGACCTCCAAATACCGTTAAGCTGGAGCCTCGGTGGCCATGCTT")







